#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors

# SketchyBar Configuration

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
# Configuring the general appearance of the bar, these are only some of the
# options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar height=44 \
  blur_radius=10 \
  position=top \
  sticky=on \
  padding_left=10 \
  padding_right=10 \
  margin=0 \
  y_offset=5 \
  corner_radius=22 \
  color=$TRANSPARENT

##### Changing Defaults #####
# We now change some default values that are applied to all further items
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

sketchybar --default icon.font="SF Pro:Semibold:16.0" \
  icon.color=$PRIMARY_COLOR \
  label.font="SF Pro:Semibold:16.0" \
  label.color=$FG_COLOR \
  padding_left=3 \
  padding_right=3 \
  icon.padding_left=6 \
  icon.padding_right=3 \
  label.padding_left=6 \
  label.padding_right=3 \
  background.corner_radius=8 \
  background.height=28 \
  background.color=$BAR_COLOR \
  background.drawing=off

# -- Left Side Items --
source $ITEM_DIR/apple_logo.sh
source $ITEM_DIR/spaces.sh
source $ITEM_DIR/front_app.sh
sketchybar --add item left_shadow_spacer left \
  --set left_shadow_spacer label.drawing=off icon.drawing=off width=0

# Start Aerospace monitor in background
$PLUGIN_DIR/aerospace_monitor.sh &

# Left section shadow background
sketchybar --add bracket left_pill_shadow apple_logo space_separator front_app left_shadow_spacer \
  --set left_pill_shadow background.color=$SHADOW_COLOR \
  background.corner_radius=8 \
  background.height=40 \
  background.padding_left=0 \
  background.padding_right=0 \
  background.y_offset=-2 \
  background.x_offset=-4 \
  background.blur_radius=0

# Left section unified background (will be updated dynamically)
sketchybar --add bracket left_pill_bg apple_logo space_separator front_app \
  --set left_pill_bg background.color=$BAR_COLOR \
  background.corner_radius=8 \
  background.height=36 \
  background.padding_left=3 \
  background.padding_right=3 \
  background.blur_radius=20

# -- Right Side Items --
source $ITEM_DIR/lock.sh
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/cpu.sh
source $ITEM_DIR/memory.sh
sketchybar --add item right_shadow_spacer right \
  --set right_shadow_spacer label.drawing=off icon.drawing=off width=0

# -- Right shadow
sketchybar --add bracket right_pill_shadow calendar lock volume battery cpu memory right_shadow_spacer \
  --set right_pill_shadow background.drawing=on \
  background.color=$SHADOW_COLOR \
  background.corner_radius=8 \
  background.height=40 \
  background.padding_left=0 \
  background.padding_right=16 \
  background.y_offset=-2 \
  background.x_offset=6 \
  background.blur_radius=0

# Right section unified background
sketchybar --add bracket right_pill_bg calendar lock volume battery cpu memory \
  --set right_pill_bg background.color=$BAR_COLOR \
  background.corner_radius=8 \
  background.height=36 \
  background.padding_left=3 \
  background.padding_right=3 \
  background.blur_radius=20

while IFS= read -r sid; do
  [ -z "$sid" ] && continue
  sketchybar --set "space.$sid" script="$PLUGIN_DIR/space.sh"
  sketchybar --subscribe "space.$sid" aerospace_workspace_change mouse.entered mouse.exited mouse.clicked
done < <(aerospace list-workspaces --all)

##### Finalizing Setup #####
# The below command is only needed at the end of the initial configuration to
# force all scripts to run the first time, it should never be run in an item script.

sketchybar --update
